
exports.seed = function(knex, Promise) {
  return Promise.join(

    knex('devs').del(),
    knex('goal').del(),
    knex('p-mang').del(),
    knex('tech').del(),

    knex('devs').insert({id: 1, name: 'Sassy Summer'}),
    knex('devs').insert({id: 2, name: 'Last Lincoln'}),
    knex('devs').insert({id: 3, name: 'Meticulous Mike'}),
    knex('devs').insert({id: 4, name: 'Meaty Mike'}),
    knex('devs').insert({id: 5, name: 'Confident Conrad'}),
    knex('devs').insert({id: 6, name: 'Jiggly James'}),
    knex('devs').insert({id: 7, name: 'Tenatious Tony'}),
    knex('devs').insert({id: 8, name: 'Mad Max'}),
    knex('devs').insert({id: 9, name: 'Camper Coleman'}),
    knex('devs').insert({id: 10, name: 'Scuba San'}),
    knex('devs').insert({id: 11, name: 'Mickey Mouse'}),
    knex('devs').insert({id: 12, name: 'Wild Will'}),
    knex('devs').insert({id: 13, name: 'Horendous Harry'}),
    knex('devs').insert({id: 14, name: 'Breaking Brad'}),
    knex('devs').insert({id: 15, name: 'Bodacious Bud'}),
    knex('devs').insert({id: 16, name: 'Subdude Seth'}),
    knex('devs').insert({id: 17, name: 'Mister Matthew'}),
    knex('devs').insert({id: 18, name: 'Classy Courtney'}),
    knex('devs').insert({id: 19, name: 'Not Nate'}),
    knex('devs').insert({id: 20, name: 'Nasty Nick'}),
    knex('devs').insert({id: 21, name: 'Magical Maddeline'}),
    knex('devs').insert({id: 22, name: 'Colorado Cooper'}),
    knex('devs').insert({id: 23, name: 'Affluent Alan'}),
    knex('devs').insert({id: 24, name: 'Phenom Phil'}),
    knex('devs').insert({id: 25, name: 'Joker Jason'}),
    knex('devs').insert({id: 26, name: 'Barbaric Blake'}),
    knex('devs').insert({id: 27, name: 'Dunkeroo Daniel'}),
    knex('tech').insert({id: 1, name: 'HTML'}),
    knex('tech').insert({id: 2, name: 'CSS'}),
    knex('tech').insert({id: 3, name: 'Javascript'}),
    knex('tech').insert({id: 4, name: 'SASS'}),
    knex('tech').insert({id: 5, name: 'Node'}),
    knex('tech').insert({id: 6, name: 'Express'}),
    knex('tech').insert({id: 7, name: 'Git'}),
    knex('tech').insert({id: 8, name: 'AJAX'}),
    knex('tech').insert({id: 9, name: 'Bootstrap'}),
    knex('goal').insert({id: 1, goal: 'World Domination!'}),
    knex('goal').insert({id: 2, goal: 'Break the Internets!'}),
    knex('goal').insert({id: 3, goal: 'Murder-Bots!'}),
    knex('goal').insert({id: 4, goal: 'Humanitarian Stuff... boring...'}),
    knex('p-mang').insert({id: 1, name: 'Emily', "s-power": 'Git-Ninja'}),
    knex('p-mang').insert({id: 2, name: 'Luke', "s-power": 'Laptop-Spike'}),
    knex('p-mang').insert({id: 3, name: 'Fabio', "s-power": 'Da Errah Defense!'}),
    knex('p-mang').insert({id: 4, name: 'Matt', "s-power": 'Deadline Extender'}),
    knex('p-mang').insert({id: 5, name: 'Akyuna', "s-power": 'Stackflow Vision'}),
    knex('p-mang').insert({id: 6, name: 'Dize', "s-power": 'Mad Computer Scientist'})
  );
};
